language: csharp

sudo: false  # use the new container-based Travis infrastructure
dist: xenial
dotnet: 2.2

before_script:
  - nvm install --lts
  - nvm use --lts
  - dotnet tool install -g fake-cli

cache:
  yarn: true

script:
  - fake build -t Build
